name: タスクリスト
description: サクッとタスクを追加したい時。又はそれほど検討しなくていい新規機能について。
title: "[タスクのカテゴリー] "
type: "Task"
body:
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: タスク内容を簡潔に説明してください。
      placeholder: 新規ページの実装
    validations:
      required: true
  - type: textarea
    id: tasklist
    attributes:
      label: タスク
      description: タスクを記入してください。順次インデントで階層分けすること。
      value: |
        - [ ]
