import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import BottomNav from "@/components/page/BottomNav";
import Header from "@/components/page/Header";
>>>>>>> origin/main

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Memoru日記",
  description:
    "ずぼらな人のための日記自動生成アプリです。写真を撮ったり一言のメモなど、その日の活動のログを通知の度に入力するだけで日記が完成します！",
>>>>>>> origin/main
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
=======
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main>{children}</main>
        <BottomNav />
>>>>>>> origin/main
      </body>
    </html>
  );
}
